### PR TITLE
initial support for radare2, update check with auto fmt replacement, Dart 3.4

### PR DESCRIPTION
**Pull request by AbhiTheModder**
- Initial Support for radare2
Just a copy for Termux of original PR as it seems worawit has been offline for quite a while, so no ETA when this will be implemented officially.
https://github.com/worawit/blutter/pull/67

- Update check and fetch/pull

- Updated for Dart 3.4.0
https://github.com/worawit/blutter/commit/690c08553779d051ee01d0c4320a9d3793b9de7a & https://github.com/worawit/blutter/commit/49a7d70b3c2608bc37700394dc74da3972c96473

### CODE REVIEW

**Comment by euzada** [comment]
@AbhiTheModder can you merge also the lates update in blutter repo. Thank you?

**Comment by AbhiTheModder** [comment]
> @AbhiTheModder can you merge also the lates update in blutter repo. Thank you?

Which ? AFAIK I've added all the latest updates already.

**Comment by euzada** [comment]
> > can you merge also the lates update in blutter repo. Thank you?
> 
> @euzada Which ? AFAIK I've added all the latest updates already.

I meant from worawit/blutter repo, see:

https://github.com/worawit/blutter/commit/690c08553779d051ee01d0c4320a9d3793b9de7a 

And 

https://github.com/worawit/blutter/commit/49a7d70b3c2608bc37700394dc74da3972c96473

**Comment by AbhiTheModder** [comment]
> > > can you merge also the lates update in blutter repo. Thank you?
> > 
> > @euzada Which ? AFAIK I've added all the latest updates already.
> 
> I meant from worawit/blutter repo, see:
> 
> https://github.com/worawit/blutter/commit/690c08553779d051ee01d0c4320a9d3793b9de7a 
> 
> And 
> 
> https://github.com/worawit/blutter/commit/49a7d70b3c2608bc37700394dc74da3972c96473

@euzada yes already done have you checked 
https://github.com/dedshit/blutter-termux/commit/790421d0081effddc925b66360e696502b8e3dd7

**Pull request merged**
